#include "../lib/_constants.cs"
#include "../lib/_eligible_scramblers.cs"

Cluster(TEAM,
        5,
        Persons(In(StringProperty(TYPE), StageVolunteer())),
        StringProperty(PRETEAM),
        [BalanceConstraint(LEADER, In(StringProperty(TYPE), Leader()), 100),
         BalanceConstraint(SIDE, (StringProperty(TYPE) == SIDE), 50),
         BalanceConstraint(TABLEMANAGER, In(TABLEMANAGER, ArrayProperty(TASKS)), 50),
         BalanceConstraint("333fm",  CompetingIn(_333fm),  25),
         BalanceConstraint("444bf",  CompetingIn(_444bf),  25),
         BalanceConstraint("555bf",  CompetingIn(_555bf),  25),
         BalanceConstraint("333mbf", CompetingIn(_333mbf), 25),
         BalanceConstraint("222",   CanScramble(_222),    1),
         BalanceConstraint("333",   CanScramble(_333),    2),
         BalanceConstraint("pyram", CanScramble(_pyram),  3),
         BalanceConstraint("skewb", CanScramble(_skewb),  4),
         BalanceConstraint("444",   CanScramble(_444),    5),
         BalanceConstraint("minx",  CanScramble(_minx),   6),
         BalanceConstraint("555",   CanScramble(_555),    7),
         BalanceConstraint("666",   CanScramble(_666),    8),
         BalanceConstraint("777",   CanScramble(_777),    9),
         BalanceConstraint("sq1",   CanScramble(_sq1),   10),
         BalanceConstraint("clock", CanScramble(_clock), 11),
         BalanceConstraint("222 semi",   (CanScramble(_222)   && (Not(CompetingIn(_222))   || (PsychSheetPosition(_222)   > 150))), 1),
         BalanceConstraint("333 semi",   (CanScramble(_333)   && (Not(CompetingIn(_333))   || (PsychSheetPosition(_333)   > 150))), 2),
         BalanceConstraint("333bf semi", (CanScramble(_333bf) && (Not(CompetingIn(_333bf)) || (PsychSheetPosition(_333bf) > 150))), 2),
         BalanceConstraint("333oh semi", (CanScramble(_333oh) && (Not(CompetingIn(_333oh)) || (PsychSheetPosition(_333oh) > 150))), 2),
         BalanceConstraint("pyram semi", (CanScramble(_pyram) && (Not(CompetingIn(_pyram)) || (PsychSheetPosition(_pyram) > 150))), 3),
         BalanceConstraint("skewb semi", (CanScramble(_skewb) && (Not(CompetingIn(_skewb)) || (PsychSheetPosition(_skewb) > 150))), 4),
         BalanceConstraint("444 semi",   (CanScramble(_444)   && (Not(CompetingIn(_444))   || (PsychSheetPosition(_444)   > 150))), 5),
         BalanceConstraint("minx semi",  (CanScramble(_minx)  && (Not(CompetingIn(_minx))  || (PsychSheetPosition(_minx)  > 150))), 6),
         BalanceConstraint("555 semi",   (CanScramble(_555)   && (Not(CompetingIn(_555))   || (PsychSheetPosition(_555)   > 150))), 7),
         BalanceConstraint("sq1 semi",   (CanScramble(_sq1)   && (Not(CompetingIn(_sq1))   || (PsychSheetPosition(_sq1)   > 150))), 8),
         BalanceConstraint("clock semi", (CanScramble(_clock) && (Not(CompetingIn(_clock)) || (PsychSheetPosition(_clock) > 150))), 9)
        ]
       )